env:
  es6: true
  browser: true
  commonjs: true
  jest: true

extends: ['airbnb', 'plugin:react/recommended']

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module

plugins: ['react', 'jsx-a11y','react-hooks', 'import']

settings:
  react:
    version: 'detect'

rules:
  react/jsx-fragments: ['off', 'syntax']
